In [32]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv('brasil_legado.csv', sep=';')

In [42]:
pd.set_option('display.max_colwidth', None)

In [43]:
df['ESTADO'] = df.LINK.apply(lambda x: x.split('/')[4])
df['CIDADE'] = df.LINK.apply(lambda x: x.split('/')[5])
df['BAIRRO'] = df.LINK.apply(lambda x: x.split('/')[6])
df['BANCO'] = df.LINK.apply(lambda x: x.split('/')[7])
df['AGENCIA'] = df.LINK.apply(lambda x: x.split('/')[8])

In [46]:
df.groupby(['ESTADO']).count()

        LINK  NOME  CIDADE  BAIRRO  BANCO  AGENCIA
ESTADO
ac        64    64      64      64     64       64
al       205   205     205     205    205      205
am       222   222     222     222    222      222
ba      1128  1128    1128    1128   1128     1128
ce       518   518     518     518    518      518
df       469   469     469     469    469      469
es       485   485     485     485    485      485
go       748   748     748     748    748      748
ma       361   361     361     361    361      361
mg      2262  2262    2262    2262   2262     2262
ms       301   301     301     301    301      301
mt       343   343     343     343    343      343
pa       530   530     530     530    530      530
pb       252   252     252     252    252      252
pe       628   628     628     628    628      628
pi       184   184     184     184    184      184
pr      1603  1603    1603    1603   1603     1603
rj      2173  2173    2173    2173   2173     2173
rn       223   223     223     223    223      223
ro       150   150     150     150    150      150
rs      1826  1826    1826    1826   1826     1826
sc       983   983     983     983    983      983
se       215   215     215     215    215      215
sp      7403  7403    7403    7403   7403     7403
to       128   128     128     128    128      128